-- JSEARCH RAW
CREATE OR REPLACE TABLE JOB_PORTAL_DB.RAW.JSEARCH_RAW (
  JOB_ID STRING,
  JOB_TITLE STRING,
  EMPLOYER_NAME STRING,
  JOB_LOCATION STRING,
  JOB_DESCRIPTION STRING,
  JOB_EMPLOYMENT_TYPE STRING,
  JOB_MIN_SALARY NUMBER,
  JOB_MAX_SALARY NUMBER,
  JOB_SALARY STRING,
  JOB_POSTED_AT_DATETIME_UTC STRING
);

-- ADZUNA RAW
CREATE OR REPLACE TABLE JOB_PORTAL_DB.RAW.ADZUNA_RAW (
  TITLE STRING,
  COMPANY_NAME STRING,
  LOCATION STRING,
  DESCRIPTION STRING,
  SALARY_MIN NUMBER,
  SALARY_MAX NUMBER,
  CONTRACT_TIME STRING,
  CREATED STRING
);

-- JOOBLE RAW
CREATE OR REPLACE TABLE JOB_PORTAL_DB.RAW.JOOBLE_RAW (
  C1 STRING,
  C2 STRING,
  C3 STRING,
  C4 STRING,
  C5 STRING,
  C6 STRING,
  C7 STRING,
  C8 STRING,
  C9 STRING,
  C10 STRING
);