CREATE OR REPLACE TABLE JOB_PORTAL_DB.CLEAN.JOB_DATA_CLEANED (
  company_name STRING,
  industry STRING,
  hq_location STRING,
  job_location STRING,
  company_size STRING,
  poster_name STRING,
  poster_role STRING,
  poster_email STRING,
  poster_phone STRING,
  job_title STRING,
  roles_and_responsibilities STRING,
  required_qualifications STRING,
  skills STRING,
  experience_required STRING,
  employment_type STRING,
  salary_min NUMBER,
  salary_max NUMBER,
  salary_currency STRING,
  salary_range STRING,
  hiring_deadline TIMESTAMP_TZ,
  source STRING,
  load_time TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);