TRUNCATE TABLE JOB_PORTAL_DB.CLEAN.JOB_DATA_CLEANED;

INSERT INTO JOB_PORTAL_DB.CLEAN.JOB_DATA_CLEANED
SELECT
  EMPLOYER_NAME,
  JOB_PUBLISHER,
  NULL,
  JOB_LOCATION,
  NULL,
  NULL, NULL, NULL, NULL,
  JOB_TITLE,
  JOB_DESCRIPTION,
  NULL,
  NULL,
  NULL,
  JOB_EMPLOYMENT_TYPE,
  JOB_MIN_SALARY,
  JOB_MAX_SALARY,
  NULL,
  JOB_SALARY,
  TO_TIMESTAMP(JOB_POSTED_AT_DATETIME_UTC),
  'JSEARCH',
  CURRENT_TIMESTAMP()
FROM JOB_PORTAL_DB.RAW.JSEARCH_RAW

UNION ALL

SELECT
  COMPANY_NAME,
  NULL,
  LOCATION,
  LOCATION,
  NULL,
  NULL,NULL,NULL,NULL,
  TITLE,
  DESCRIPTION,
  NULL,
  NULL,
  NULL,
  CONTRACT_TIME,
  SALARY_MIN,
  SALARY_MAX,
  NULL,
  CONCAT(SALARY_MIN,' - ',SALARY_MAX),
  TO_TIMESTAMP(CREATED),
  'ADZUNA',
  CURRENT_TIMESTAMP()
FROM JOB_PORTAL_DB.RAW.ADZUNA_RAW

UNION ALL

SELECT
  C8,
  NULL,
  C2,
  C2,
  NULL,
  NULL,NULL,NULL,NULL,
  C1,
  C3,
  NULL,
  NULL,
  NULL,
  C6,
  NULL,
  NULL,
  NULL,
  C4,
  CURRENT_TIMESTAMP(),
  'JOOBLE',
  CURRENT_TIMESTAMP()
FROM JOB_PORTAL_DB.RAW.JOOBLE_RAW;